model_list:
  - model_name: chatgpt/gpt-6-luna
    model_info:
      mode: responses
    litellm_params:
      model: chatgpt/gpt-6-luna
      reasoning_effort: medium


  - model_name: chatgpt/gpt-5.4
    model_info:
      mode: responses
      input_cost_per_token: 0.0000025
      cache_read_input_token_cost: 0.00000025
      output_cost_per_token: 0.000015
      input_cost_per_token_above_272k_tokens: 0.000005
      cache_read_input_token_cost_above_272k_tokens: 0.0000005
      output_cost_per_token_above_272k_tokens: 0.0000225
    litellm_params:
      model: chatgpt/gpt-5.4
      reasoning_effort: medium

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
